### ISSUE TITLE
SL6 環境でサンプルコードを実行するとエラーが出ます

### ISSUE THREAD

**Issue by yanaken0** [yuasatakayuki/RubyFits#9]
サンプルコードを実行したところ、私の環境ではエラーが発生することに気付きました。

### エラーの状況
createNewTable.rb,newTable.rb でエラーが発生します。
ちなみに他の全てのサンプルコードではエラーは発生しません。

> $ ruby createNewTable.rb
 createNewTable.rb:23:in 'resize_rows': Expected argument 0 of type fits_table *, but got 
 Fits::FitsTableHDU #<Fits::FitsTableHDU:0x0000000... (ObjectPreviouslyDeleted)
	in SWIG method 'resize_rows'
	from createNewTable.rb:23:in '\<main\>'

> $ ruby newTable.rb
newTable.rb:19:in 'resize_rows': Expected argument 0 of type fits_table *, but got Fits::FitsTableHDU #<Fits::FitsTableHDU:0x0000000... (ObjectPreviouslyDeleted)
	in SWIG method 'resize_rows'
	from newTable.rb:19:in '\<main\>'
### 環境
> OS: Scientific Linux 6
$ uname -a
Linux wfcana 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 11:25:51 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
$ cmake --version
cmake version 2.8.9
sllib-1.4.2f
sfitsio-1.4.4
RubyFits のソースファイルの日付は、2015 Jan 3 です。

**Comment by yuasatakayuki** [comment]
@yanaken0 さん

ご連絡ありがとうございます。

上記の件ですが、こちらでも試してみたところ、SLCのyumのデフォルトでインストールされるSWIGのバージョンが古いことが原因のようです。デフォルトのSWIGでは、報告いただいたのと同じエラーがでました。

[gistにアップロードしたScientific Linux + RubyFitsのDockerfile](https://gist.github.com/yuasatakayuki/f61befcff620e8e558fb4a03d547a416)で構築したDockerコンテナ内で試してみると、

```
[root@c83173352028 example]# uname -a
Linux c83173352028 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@c83173352028 example]# swig -version

SWIG Version 3.0.2

Compiled with g++ [x86_64-unknown-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
[root@c83173352028 example]# pwd
/root/RubyFits/example
[root@c83173352028 example]# ruby createNewTable.rb
/usr/local/lib/ruby/RubyFits.rb:780: warning: constant ::Fixnum is deprecated
FitsTableHDU  nColumns=1 nRows=128
[root@c83173352028 example]# ls createNewTable.fits
createNewTable.fits
[root@c83173352028 example]# ls -l createNewTable.fits
-rw-r--r-- 1 root root 8640 Apr 20 16:47 createNewTable.fits
[root@c83173352028 example]# 
```

となり、エラーになりませんでした。

お手元のSWIGをアップデートして試してみていただけますでしょうか。他の関数も正しくSWIGで変換されているかわかりませんので、再度RubyFits全体をインストールしていただくのが安全と思います。

今後も何かありましたらご連絡ください。
